### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by madjam002** [burt202/table-tennis-scoring#1]
Is there an API available to fetch the results?

I'm currently screen scraping the website and parsing the response myself.

**Comment by burt202** [comment]
Not currently, but its doable. I'm thinking a [league_name]-results.json file where you get all of the results grouped by date. Sound reasonable?

Also whats your plan?

**Comment by madjam002** [comment]
I'm working on an app called TableTennisHub 2 which collates results from various leagues, currently screen scraping for all of them.

**Comment by burt202** [comment]
#brilliant
